### ISSUE TITLE
NcDateTimePicker needs design update for Nextcloud 30

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud-libraries/nextcloud-vue#5951]
![image](https://github.com/user-attachments/assets/7ed2cbb8-77ff-4c6d-80e6-305e3fdb4f79)

**Comment by susnux** [comment]
In words:
- [ ] Border width need to use the new two variable (input & input-focused)
- [ ] Border color on hover & focus should be `--color-main-text` and not primary like all other inputs
- [ ] The placeholder has a default `opacity` set, this should be removed as the color should be `--color-text-maxcontrast`

**Comment by Antreesy** [comment]
- [ ] Prominent "Back to date selection" button: https://github.com/nextcloud-libraries/nextcloud-vue/issues/1440

**Comment by susnux** [comment]
#6651
